[package]
name = "thinkerbell"
version = "0.1.0"
authors = ["David Rajchenbach-Teller <david.teller@univ-orleans.fr>"]

[dependencies]
rustc-serialize = "0.3.16"
itertools = "0.4.7"
chrono = "0.2.19"
